### ISSUE TITLE
Awesome! It also works in other environments :)

### ISSUE THREAD

**Issue by fonsp** [hellemo/ShortCodes.jl#15]
Hey, loving this small but useful package, I will definitely use it myself in the future!

A little observation is that this package probably also works in other environments, such as: Jupyter, Olive.jl, Documenter.jl, Franklin and maybe more! Because these environments use the same `show` method for displaying cell results inside the page.

**Comment by AshtonSBradley** [comment]
Yes, this is such a useful package. I already got quite dependent on it

**Comment by hellemo** [comment]
Thanks! Great to hear that you find it useful :-)

I'll make a note that it probably works in other environments too in the README, I haven't tested it because I mostly only use Pluto these days.

@AshtonSBradley citation data for grant applications was the original motivation for adding dois
