### ISSUE TITLE
author order scrambled

### ISSUE THREAD

**Issue by AshtonSBradley** [hellemo/ShortCodes.jl#19]
there seems to be some randomness to author order returning from the DOI call:

`DOI("10.1080/00018730802564254")`

returns

Bradley, A S; Davis, M J; Blakie, P. Blair; Ballagh, R.J.; Gardiner, C.W. Dynamics And Statistical Mechanics Of Ultra-Cold Bose Gases Using C-Field Techniques, Advances In Physics (2008) [10/btkg97](https://doi.org/10/btkg97), cited by 387

But the article is

P. B. Blakie, A. S. Bradley, M. J. Davis, R. J. Ballagh, and C. W. Gardiner, Dynamics and Statistical Mechanics of Ultra-Cold Bose Gases Using c-Field Techniques, Advances in Physics 57, 363 (2008).

Is this ShortCodes, or opencitations?

**Comment by hellemo** [comment]
ShortCodes doesn't change the order, this looks like a data issue with opencitations: 

https://opencitations.net/index/search?text=10.1080%2F00018730802564254

**Comment by arcangelo7** [comment]
Thank you for reporting this problem. I confirm that the problem was with OpenCitations; there was a bug in the API. I fixed it

**Comment by hellemo** [comment]
Thanks @arcangelo7
