### ISSUE TITLE
broken example link in the readme

### ISSUE THREAD

**Issue by CarloLucibello** [hellemo/ShortCodes.jl#9]
If I clink on the example in 

The basic usage is shown below, check out the [example](https://htmlpreview.github.io/?https://github.com/hellemo/ShortCodes.jl/blob/main/examples/static-demo.html) to get an impression of the resulting page.

I land on black page

**Comment by hellemo** [comment]
Thanks for reporting, there seems to be a problem with the html previewer. I try switching to raw.githack in #10 , hope that solves the problem.
